### ISSUE TITLE
undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by sohee-zoe** [charlesq34/pointnet-autoencoder#10]
I use 

> Ubuntu 18.04 / python 3.6 / Cuda 10.0 / tensorflow 1.9

(py36_gpu) sohee@IPIS-sohee:~/coding/pointnet-autoencoder$ python train.py --model model --log_dir log_chair_norotation --num_point 2048 --category Chair --no_rotation

> Traceback (most recent call last):
>   File "train.py", line 48, in <module>
>     MODEL = importlib.import_module(FLAGS.model) # import network module
>   File "/home/sohee/anaconda3/envs/py36_gpu/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/sohee/coding/pointnet-autoencoder/models/model.py", line 17, in <module>
>     import tf_nndistance
>   File "/home/sohee/coding/pointnet-autoencoder/tf_ops/nn_distance/tf_nndistance.py", line 12, in <module>
>     nn_distance_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_nndistance_so.so'))
>   File "/home/sohee/anaconda3/envs/py36_gpu/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> **tensorflow.python.framework.errors_impl.NotFoundError: /home/sohee/coding/pointnet-autoencoder/tf_ops/nn_distance/tf_nndistance_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv**
> 

tf_ops/nn_distance/tf_nn_distance_compile.sh

> #/bin/bash
> CUDA_ROOT=/usr/local/cuda-10.0
> TF_ROOT=/home/user/.local/lib/python3.6/site-packages/tensorflow
> 
> TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
> TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
> 
> /usr/local/cuda-10.0/bin/nvcc tf_nndistance_g.cu -o tf_nndistance_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
> 
> g++ -std=c++11 tf_nndistance.cpp tf_nndistance_g.cu.o -o tf_nndistance_so.so -shared -fPIC -I$TF_INC/ -I$TF_INC/external/nsync/public -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -L$TF_LIB -ltensorflow_framework -I$CUDA_ROOT/include -lcudart -L$CUDA_ROOT/lib64/ -O2 -D_GLIBCXX_USE_CXX11_ABI=0
> 

/tf_ops/approxmatch/tf_approxmatch_compile.sh

> 
> #/bin/bash
> 
> CUDA_ROOT=/usr/local/cuda-10.0
> TF_ROOT=/home/user/.local/lib/python3.6/site-packages/tensorflow
> 
> 
> TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
> TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
> 
> 
> 
> CUDA_ROOT/bin/nvcc tf_approxmatch_g.cu -o tf_approxmatch_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
> 
> 
> g++ -std=c++11 tf_approxmatch.cpp tf_approxmatch_g.cu.o -o tf_approxmatch_so.so -shared -fPIC -I$TF_INC/ -I$TF_INC/external/nsync/public -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -L$TF_LIB -ltensorflow_framework -I$CUDA_ROOT/include -lcudart -L$CUDA_ROOT/lib64/ -O2 -D_GLIBCXX_USE_CXX11_ABI=0
> 
> 
>

**Comment by SkylerHuang** [comment]
i set -D_GLIBCXX_USE_CXX11_ABI=1, complie it successfully

**Comment by xiaoself1990** [comment]
> i set -D_GLIBCXX_USE_CXX11_ABI=1, complie it successfully

Hallo @SkylerHuang , i got the same problem, can you please tell me which enviroment did you use? Thanks a lot!

**Comment by SkylerHuang** [comment]
Hello @xiaoself1990, my environment is Ubuntu 18.04.2, Python2.7, GCC 7.3.0, Cudn 10.0, Tensorflow 1.13.1

**Comment by ReallyPuzzle** [comment]
> i set -D_GLIBCXX_USE_CXX11_ABI=1, complie it successfully

This is useful!

**Comment by bodhicheng** [comment]
The problem is caused by the difference between the local and compiled gcc versions of tensorflow.
Conda's tensorflow is compiled by gcc7. My local version is 4.8. When I installed with pip, the problem was solved.

**Comment by AmrMoataz** [comment]
> i set -D_GLIBCXX_USE_CXX11_ABI=1, complie it successfully

in which file can i do this ?

**Comment by bodhicheng** [comment]
> > i set -D_GLIBCXX_USE_CXX11_ABI=1, complie it successfully
> 
> in which file can i do this ?

It is a parameter of g++ command. You should set it in the compile command.

**Comment by FeiDao7943** [comment]
I just avoid this issue in change  version of g++, gcc, TF, and CUDA. 
It works on both colab and physical computers.
You can try in this environment, that seems not so reasonable but effective.

Ubuntu 18.04.5 LTS 
tensorflow-gpu==1.13.1
numpy==1.16.0 (this might be the key)
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CUDA 10.0

And "-D_GLIBCXX_USE_CXX11_ABI=0" in the "tf_xxxx_complie.sh" should be deleted
