### ISSUE TITLE
High Density of Predicted Points in Output

### ISSUE THREAD

**Issue by ninasinger** [charlesq34/pointnet-autoencoder#17]
Hi, 
I am trying to implement this code for the generation of points from an aerial LiDAR system. I am able to reproduce the ModelNet results but when I try to predict points from my own dataset, after retraining, I am getting a very dense set of points in the middle. Do you have any guesses why this might be or suggestions for adjustments I could make?
Thanks 
<img width="401" alt="Screen Shot 2021-02-01 at 9 26 44 AM" src="https://user-images.githubusercontent.com/12926981/106471726-f042f700-646f-11eb-9ba5-24929e295b35.png">

**Comment by Limpingdragon03** [comment]
Hello @ninasinger how did you figure out the above issue?
It would be very helpful if you could shed some light on the approach you took. Did you change the intermediate layers of the Encoder as well as the Decoder with some newer operations PointConvolution?
I have exactly the same issue.

Any help would be greatly appreciated. Thanks in advance!
